# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python\Lessons\Code\实战开发02-多功能工具箱\ui\dialog_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(250, 259)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingDialog.sizePolicy().hasHeightForWidth())
        SettingDialog.setSizePolicy(sizePolicy)
        SettingDialog.setMinimumSize(QtCore.QSize(0, 0))
        SettingDialog.setMaximumSize(QtCore.QSize(9999999, 9999999))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(SettingDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.groupBox)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.cb_port = QtWidgets.QComboBox(self.groupBox)
        self.cb_port.setObjectName("cb_port")
        self.cb_port.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_port)
        self.Label_2 = QtWidgets.QLabel(self.groupBox)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.cb_baudrate = QtWidgets.QComboBox(self.groupBox)
        self.cb_baudrate.setObjectName("cb_baudrate")
        self.cb_baudrate.addItem("")
        self.cb_baudrate.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_baudrate)
        self.Label_3 = QtWidgets.QLabel(self.groupBox)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.ComboBox = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox.setObjectName("ComboBox")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ComboBox)
        self.Label_4 = QtWidgets.QLabel(self.groupBox)
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.ComboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_2.setObjectName("ComboBox_2")
        self.ComboBox_2.addItem("")
        self.ComboBox_2.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ComboBox_2)
        self.Label_5 = QtWidgets.QLabel(self.groupBox)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.ComboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_3.setObjectName("ComboBox_3")
        self.ComboBox_3.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ComboBox_3)
        self.Label_6 = QtWidgets.QLabel(self.groupBox)
        self.Label_6.setObjectName("Label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.ComboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.ComboBox_4.setObjectName("ComboBox_4")
        self.ComboBox_4.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ComboBox_4)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(SettingDialog)
        self.buttonBox.accepted.connect(SettingDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SettingDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Dialog"))
        self.groupBox.setTitle(_translate("SettingDialog", "设置"))
        self.Label.setText(_translate("SettingDialog", "端口号："))
        self.cb_port.setItemText(0, _translate("SettingDialog", "COM6"))
        self.Label_2.setText(_translate("SettingDialog", "波特率："))
        self.cb_baudrate.setItemText(0, _translate("SettingDialog", "9600"))
        self.cb_baudrate.setItemText(1, _translate("SettingDialog", "115200"))
        self.Label_3.setText(_translate("SettingDialog", "数据位："))
        self.ComboBox.setItemText(0, _translate("SettingDialog", "8"))
        self.ComboBox.setItemText(1, _translate("SettingDialog", "9"))
        self.Label_4.setText(_translate("SettingDialog", "停止位："))
        self.ComboBox_2.setItemText(0, _translate("SettingDialog", "1"))
        self.ComboBox_2.setItemText(1, _translate("SettingDialog", "2"))
        self.Label_5.setText(_translate("SettingDialog", "校验位："))
        self.ComboBox_3.setItemText(0, _translate("SettingDialog", "None"))
        self.Label_6.setText(_translate("SettingDialog", "流控制："))
        self.ComboBox_4.setItemText(0, _translate("SettingDialog", "None"))
