# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python\Lessons\Code\06-上位机开发-PyQt5\ui\my_regist_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWidget(object):
    def setupUi(self, RegisterWidget):
        RegisterWidget.setObjectName("RegisterWidget")
        RegisterWidget.resize(464, 451)
        RegisterWidget.setMaximumSize(QtCore.QSize(480, 640))
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(RegisterWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(RegisterWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(RegisterWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(RegisterWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(RegisterWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(RegisterWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(RegisterWidget)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(RegisterWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(RegisterWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(RegisterWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(RegisterWidget)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(RegisterWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(RegisterWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(RegisterWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(RegisterWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 5, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(RegisterWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(RegisterWidget)
        QtCore.QMetaObject.connectSlotsByName(RegisterWidget)

    def retranslateUi(self, RegisterWidget):
        _translate = QtCore.QCoreApplication.translate
        RegisterWidget.setWindowTitle(_translate("RegisterWidget", "红娘网注册"))
        self.label.setText(_translate("RegisterWidget", "用户名"))
        self.label_2.setText(_translate("RegisterWidget", "密码"))
        self.label_4.setText(_translate("RegisterWidget", "性别"))
        self.radioButton.setText(_translate("RegisterWidget", "男♂"))
        self.radioButton_2.setText(_translate("RegisterWidget", "女♀"))
        self.label_5.setText(_translate("RegisterWidget", "爱好"))
        self.checkBox.setText(_translate("RegisterWidget", "抽烟🚬"))
        self.checkBox_2.setText(_translate("RegisterWidget", "喝酒🍺"))
        self.checkBox_3.setText(_translate("RegisterWidget", "烫头🦱"))
        self.label_3.setText(_translate("RegisterWidget", "个性签名"))
        self.label_6.setText(_translate("RegisterWidget", "个性签名"))
        self.pushButton.setText(_translate("RegisterWidget", "确认注册"))
